cfg:
  sample_rate: 16000
  log_prediction: true
  ctc_reduction: mean_batch
  skip_nan_grad: false
  train_ds:
    manifest_filepath: /home/saurabh/manifest/new/kanada_labelled/train.json
    sample_rate: 16000
    batch_size: 16
    shuffle: true
    num_workers: 8
    pin_memory: true
    use_start_end_token: false
    trim_silence: false
    max_duration: 16.7
    min_duration: 0.1
    is_tarred: false
    tarred_audio_filepaths: null
    shuffle_n: 2048
    bucketing_strategy: synced_randomized
    bucketing_batch_size: null
  validation_ds:
    manifest_filepath: /home/saurabh/manifest/new/kanada_labelled/valid.json
    sample_rate: 16000
    batch_size: 16
    shuffle: false
    num_workers: 8
    pin_memory: true
    use_start_end_token: false
  test_ds:
    manifest_filepath: null
    sample_rate: 16000
    batch_size: 16
    shuffle: false
    num_workers: 8
    pin_memory: true
    use_start_end_token: false
  tokenizer:
    dir: /home/saurabh/manifest/new/kanada_labelled/spe/tokenizer_spe_bpe_v100/
    type: bpe
  preprocessor:
    _target_: nemo.collections.asr.modules.AudioToMelSpectrogramPreprocessor
    sample_rate: 16000
    normalize: per_feature
    window_size: 0.025
    window_stride: 0.01
    window: hann
    features: 80
    n_fft: 512
    log: true
    frame_splicing: 1
    dither: 1.0e-05
    pad_to: 0
    pad_value: 0.0
  spec_augment:
    _target_: nemo.collections.asr.modules.SpectrogramAugmentation
    freq_masks: 2
    time_masks: 10
    freq_width: 27
    time_width: 0.05
    rect_masks: 0
  encoder:
    _target_: nemo.collections.asr.modules.ConformerEncoder
    feat_in: 80
    feat_out: -1
    n_layers: 16
    d_model: 176
    subsampling: striding
    subsampling_factor: 4
    subsampling_conv_channels: -1
    causal_downsampling: false
    ff_expansion_factor: 4
    self_attention_model: rel_pos
    n_heads: 4
    att_context_size:
    - -1
    - -1
    att_context_style: regular
    xscaling: true
    untie_biases: true
    pos_emb_max_len: 5000
    conv_kernel_size: 31
    conv_norm_type: batch_norm
    conv_context_size: null
    dropout: 0.1
    dropout_pre_encoder: 0.1
    dropout_emb: 0.0
    dropout_att: 0.1
    stochastic_depth_drop_prob: 0.0
    stochastic_depth_mode: linear
    stochastic_depth_start_layer: 1
  decoder:
    _target_: nemo.collections.asr.modules.ConvASRDecoder
    feat_in: null
    num_classes: 100
    vocabulary:
    - <unk>
    - ತ್
    - ಲ್
    - ಗಳ
    - ▁ಅ
    - ▁ಸ
    - ನ್
    - ಲ್ಲ
    - ▁ಮ
    - ತ್ತ
    - ಾಗ
    - ▁ಕ
    - ನ್ನ
    - ್ರ
    - ಂದ
    - ರ್
    - ▁ಪ
    - ಲ್ಲಿ
    - ▁ವ
    - ನ್ನು
    - ▁ನ
    - ರು
    - ರಿ
    - ್ಯ
    - ▁ಹ
    - ೆಯ
    - ▁ಬ
    - ಕ್
    - ಿದ
    - ▁ಇ
    - ಿಸ
    - ಂತ
    - ವು
    - ್ಟ
    - ಾರ
    - ದು
    - ಿಯ
    - ುತ್ತ
    - ▁
    - ್
    - ಿ
    - ು
    - ರ
    - ದ
    - ಾ
    - ತ
    - ನ
    - ವ
    - ಗ
    - ೆ
    - ಲ
    - ಕ
    - ಯ
    - ಂ
    - ಸ
    - ಳ
    - ಮ
    - ಪ
    - ಅ
    - ಬ
    - ಹ
    - ಟ
    - ಡ
    - ೇ
    - ೂ
    - ಶ
    - ಣ
    - ೊ
    - ೀ
    - ಷ
    - ಚ
    - ಇ
    - ಜ
    - ಧ
    - ೋ
    - ಥ
    - ಭ
    - ಆ
    - ಎ
    - ಒ
    - ಈ
    - ಉ
    - ಖ
    - ೈ
    - ೃ
    - ೌ
    - ಘ
    - ಫ
    - ಞ
    - ಏ
    - ಐ
    - ಃ
    - ಠ
    - ಛ
    - ಔ
    - ಢ
    - ಊ
    - ಋ
    - ಓ
    - ಝ
  interctc:
    loss_weights: []
    apply_at_layers: []
  optim:
    name: adamw
    lr: 2.0
    betas:
    - 0.9
    - 0.98
    weight_decay: 0.001
    sched:
      name: NoamAnnealing
      d_model: 176
      warmup_steps: 10000
      warmup_ratio: null
      min_lr: 1.0e-06
  target: nemo.collections.asr.models.ctc_bpe_models.EncDecCTCModelBPE
  nemo_version: 1.17.0rc0
